services:
  - type: web
    name: meine-ki
    runtime: python
    pythonVersion: 3.11.9
    buildCommand: pip cache purge && pip install --no-cache-dir -r requirements.txt
    startCommand: exec gunicorn app:app
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: true
      - key: PYTHONDONTWRITEBYTECODE
        value: true
